import { env } from "cloudflare:workers";
import { bookingResponse } from "../../../../../lib/booking-http.ts";
import { BookingError } from "../../../../../lib/booking-policy.ts";
import { getMarketingContent } from "../../../../../lib/marketing-content.ts";
import { getMenuContent } from "../../../../../lib/menu-content.ts";
import { getOperations } from "../../../../../lib/operations-config.ts";
import { getSeoContent, validateSeo } from "../../../../../lib/seo-content.ts";
function authorize(request:Request){if(!env.ADMIN_API_KEY||request.headers.get("x-admin-key")!==env.ADMIN_API_KEY)throw new BookingError(401,"UNAUTHORIZED","Nicht autorisiert.");if(!env.OPENAI_API_KEY)throw new BookingError(503,"AI_NOT_CONFIGURED","AI-Vorschläge sind noch nicht konfiguriert. Hinterlegen Sie OPENAI_API_KEY in der Produktionsumgebung.")}
export async function POST(request:Request){return bookingResponse(async()=>{authorize(request);const [{config},{content:menu},{content:marketing},{content:current}]=await Promise.all([getOperations(env.DB),getMenuContent(env.DB),getMarketingContent(env.DB),getSeoContent(env.DB)]);const facts={restaurant:config.restaurant,menu:menu.dishes.map(d=>({name:d.name.de,description:d.description.de,available:d.available})),events:marketing.events.filter(e=>e.published).map(e=>({title:e.title.de,summary:e.summary.de,date:e.date})),current};const schema={type:"object",additionalProperties:false,properties:{pages:{type:"object",additionalProperties:false,properties:Object.fromEntries(["home","menu","events","reservation"].map(id=>[id,{type:"object",additionalProperties:false,properties:{title:{type:"string"},description:{type:"string"}},required:["title","description"]}])),required:["home","menu","events","reservation"]},keywords:{type:"array",items:{type:"string"}},serviceAreas:{type:"array",items:{type:"string"}},brandSummary:{type:"string"}},required:["pages","keywords","serviceAreas","brandSummary"]};const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{authorization:`Bearer ${env.OPENAI_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({model:env.OPENAI_MODEL||"gpt-5-mini",store:false,instructions:"Act as a German local restaurant SEO editor. Use only supplied facts. Never invent awards, location details, menu items, prices, or claims. Titles max 60 characters, descriptions max 155 characters. Return useful natural German, not keyword stuffing.",input:JSON.stringify(facts),text:{format:{type:"json_schema",name:"seo_suggestion",strict:true,schema}}})});const result=await response.json() as any;if(!response.ok)throw new BookingError(502,"AI_FAILED",result?.error?.message||"AI-Vorschlag konnte nicht erstellt werden.");const output=result.output_text||result.output?.flatMap((item:any)=>item.content||[]).find((item:any)=>item.type==="output_text")?.text;if(!output)throw new BookingError(502,"AI_FAILED","Die AI hat keinen Vorschlag geliefert.");return{suggestion:validateSeo(JSON.parse(output))}})}
