"use client";
import Image from "next/image";
import { useState } from "react";
import { ArrowRight, Check } from "lucide-react";
import { SiteHeader } from "../../components/site-header";
import tables from "../../data/tables.json";

export default function Reservation(){
  const [step,setStep]=useState(1),[date,setDate]=useState("2026-09-18"),[time,setTime]=useState("19:30"),[guests,setGuests]=useState(4),[selected,setSelected]=useState("restaurant-choice"),[saving,setSaving]=useState(false),[error,setError]=useState(""),[id,setId]=useState("");
  const chosen=tables.find(t=>t.id===selected);
  async function submit(e:React.FormEvent<HTMLFormElement>){
    e.preventDefault();setSaving(true);setError("");const f=new FormData(e.currentTarget);
    const response=await fetch("/api/reservations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({date,time,guestCount:guests,tableId:selected,customer:{name:f.get("name"),phone:f.get("phone"),email:f.get("email")},occasion:f.get("occasion"),dietary:f.get("dietary"),notes:f.get("notes")})});
    const result=await response.json();setSaving(false);
    if(!response.ok){setError(result.error||"Die Reservierung konnte nicht gespeichert werden.");if(result.alternatives?.length)setStep(2);return}
    setId(result.reservation.id);setStep(4);
  }
  return <main className="min-h-screen bg-[#0b1712] text-[#f5e8d3]"><SiteHeader/>
    <div className="mx-auto max-w-7xl px-5 py-10 sm:px-10">
      {step<4&&<ol className="mx-auto mb-12 flex max-w-xl justify-between">{["Termin","Tisch","Details"].map((x,i)=><li key={x} className="flex items-center gap-2"><span className={`grid h-10 w-10 place-items-center rounded-full border ${i+1<=step?"border-[#c68a3b] text-[#d6a45f]":"border-white/20 text-white/30"}`}>{i+1<step?<Check size={17}/>:i+1}</span><span className="hidden sm:inline">{x}</span></li>)}</ol>}
      {step===1&&<section className="mx-auto max-w-3xl rounded-3xl bg-[#fff8ec] p-7 text-[#10261e] sm:p-10"><p className="eyebrow">Schritt 1 von 3</p><h1 className="font-display mt-3 text-5xl">Wann dürfen wir Sie begrüßen?</h1><div className="mt-9 grid gap-5 sm:grid-cols-3"><label className="grid gap-2 text-sm">Datum<input value={date} onChange={e=>setDate(e.target.value)} type="date" className="rounded-xl border bg-white px-4 py-4"/></label><label className="grid gap-2 text-sm">Uhrzeit<select value={time} onChange={e=>setTime(e.target.value)} className="rounded-xl border bg-white px-4 py-4">{["18:00","18:30","19:00","19:30","20:00","20:30"].map(x=><option key={x}>{x}</option>)}</select></label><label className="grid gap-2 text-sm">Gäste<select value={guests} onChange={e=>setGuests(+e.target.value)} className="rounded-xl border bg-white px-4 py-4">{[1,2,3,4,5,6,7,8].map(x=><option key={x}>{x}</option>)}</select></label></div><button onClick={()=>setStep(2)} className="mt-8 flex w-full items-center justify-between rounded-full bg-[#a52520] px-6 py-4 font-semibold text-white">Passende Tische anzeigen <ArrowRight/></button></section>}
      {step===2&&<section><p className="eyebrow">Schritt 2 von 3</p><h1 className="font-display mt-3 text-5xl">Ihr Tisch</h1><p className="mt-3 text-white/55">{date} · {time} Uhr · {guests} Personen</p><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-4"><button onClick={()=>setSelected("restaurant-choice")} className={`rounded-2xl border p-6 text-left ${selected==="restaurant-choice"?"border-[#d6a45f] bg-[#fff8ec] text-[#10261e]":"border-white/15"}`}><Check/><h2 className="font-display mt-7 text-2xl">Restaurant wählt</h2><p className="mt-3 text-sm opacity-60">Wir wählen den besten verfügbaren Tisch.</p></button>{tables.filter(t=>t.capacity>=guests).map(t=><button key={t.id} onClick={()=>setSelected(t.id)} className={`overflow-hidden rounded-2xl bg-[#fff8ec] text-left text-[#10261e] ${selected===t.id?"ring-2 ring-[#d6a45f]":""}`}><div className="relative aspect-[4/3]"><Image src={t.image} fill alt={t.name} className="object-cover" sizes="25vw"/></div><div className="p-5"><h2 className="font-display text-2xl">{t.name} · {t.area.de}</h2><p className="mt-2 text-sm text-[#10261e]/55">{t.feature.de}</p></div></button>)}</div>{error&&<p className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<div className="mt-8 flex gap-4"><button onClick={()=>setStep(1)} className="button-secondary">Zurück</button><button onClick={()=>setStep(3)} className="button-primary">Weiter <ArrowRight/></button></div></section>}
      {step===3&&<section className="mx-auto grid max-w-5xl gap-7 lg:grid-cols-[1fr_320px]"><form onSubmit={submit} className="rounded-3xl bg-[#fff8ec] p-7 text-[#10261e] sm:p-10"><p className="eyebrow">Schritt 3 von 3</p><h1 className="font-display mt-3 text-5xl">Ihre Details</h1><div className="mt-8 grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm">Name<input name="name" required className="rounded-xl border bg-white px-4 py-3"/></label><label className="grid gap-2 text-sm">Telefon<input name="phone" required className="rounded-xl border bg-white px-4 py-3"/></label><label className="grid gap-2 text-sm sm:col-span-2">E-Mail<input name="email" type="email" required className="rounded-xl border bg-white px-4 py-3"/></label><label className="grid gap-2 text-sm">Anlass<select name="occasion" className="rounded-xl border bg-white px-4 py-3"><option>Kein Anlass</option><option>Geburtstag</option><option>Jahrestag</option></select></label><label className="grid gap-2 text-sm">Ernährung<select name="dietary" className="rounded-xl border bg-white px-4 py-3"><option>Keine Angabe</option><option>Vegetarisch</option><option>Vegan</option></select></label><label className="grid gap-2 text-sm sm:col-span-2">Allergien oder Wünsche<textarea name="notes" rows={3} className="rounded-xl border bg-white px-4 py-3"/></label></div><label className="mt-5 flex gap-3 text-sm"><input required type="checkbox"/>Ich akzeptiere die Reservierungsbedingungen.</label>{error&&<p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<button disabled={saving} className="mt-7 flex w-full items-center justify-between rounded-full bg-[#a52520] px-6 py-4 font-semibold text-white disabled:opacity-60">{saving?"Wird geprüft…":"Reservierung anfragen"}<ArrowRight/></button></form><aside className="h-fit rounded-2xl border border-[#c68a3b]/30 p-6"><p className="eyebrow">Zusammenfassung</p><p className="mt-5">{date}<br/>{time} Uhr · {guests} Personen</p><p className="mt-4">{chosen?`${chosen.name} · ${chosen.area.de}`:"Tischwahl durch Restaurant"}</p><button onClick={()=>setStep(2)} className="mt-5 text-[#d6a45f]">Auswahl ändern</button></aside></section>}
      {step===4&&<section className="mx-auto max-w-2xl py-20 text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-[#c68a3b] text-[#10261e]"><Check size={30}/></span><p className="eyebrow mt-8">Reservierungsanfrage {id}</p><h1 className="font-display mt-3 text-5xl">Bis bald bei Bailamos.</h1><p className="mt-5 text-lg text-white/65">Ihre Reservierung wurde gespeichert und wartet auf Bestätigung.</p><a href="/" className="button-secondary mt-8">Zur Startseite</a></section>}
    </div>
  </main>
}
