"use client";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { Bell, CalendarDays, Check, ChevronRight, LayoutDashboard, Menu as MenuIcon, Plus, Search, Settings, TableProperties, Users } from "lucide-react";
import menu from "../../data/menu.json";

const reservations=[{time:"18:00",name:"Müller",guests:2,table:"Tisch 08",status:"Bestätigt"},{time:"18:30",name:"Schneider",guests:4,table:"Tisch 16",status:"Ausstehend"},{time:"19:00",name:"Weber",guests:2,table:"Tisch 12",status:"Bestätigt"},{time:"19:30",name:"Fischer",guests:6,table:"Tisch 04",status:"Bestätigt"}];
export default function Admin(){const [view,setView]=useState("Übersicht");return <main className="min-h-screen bg-[#f4f0e8] text-[#10261e] lg:grid lg:grid-cols-[250px_1fr]">
  <aside className="bg-[#0b1712] px-5 py-6 text-[#f5e8d3] lg:min-h-screen"><Link href="/" className="flex items-center gap-3"><Image src="/bailamos-logo.jpg" width={52} height={52} alt="Bailamos" className="h-12 w-12 rounded-full object-cover"/><div><p className="font-display text-xl">BAILAMOS</p><p className="text-xs text-white/45">Administration</p></div></Link><nav className="mt-10 grid grid-cols-3 gap-2 lg:grid-cols-1">{[["Übersicht",LayoutDashboard],["Reservierungen",CalendarDays],["Menü",MenuIcon],["Tische",TableProperties],["Einstellungen",Settings]].map(([label,Icon])=><button key={label as string} onClick={()=>setView(label as string)} className={`flex items-center gap-3 rounded-xl px-4 py-3 text-left text-sm ${view===label?"bg-[#c68a3b] text-[#10261e]":"text-white/65 hover:bg-white/5"}`}><Icon size={18}/><span className="hidden lg:inline">{label as string}</span></button>)}</nav></aside>
  <section className="p-5 sm:p-8 lg:p-10"><header className="flex items-center justify-between"><div><p className="text-sm text-[#10261e]/50">Freitag, 11. September 2026</p><h1 className="font-display mt-1 text-4xl">{view}</h1></div><div className="flex items-center gap-3"><button className="relative grid h-11 w-11 place-items-center rounded-full bg-white"><Bell size={19}/><span className="absolute right-0 top-0 grid h-5 w-5 place-items-center rounded-full bg-[#a52520] text-[10px] text-white">3</span></button><div className="grid h-11 w-11 place-items-center rounded-full bg-[#10261e] text-sm text-white">CM</div></div></header>
  {view==="Übersicht"&&<><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Reservierungen heute","28",CalendarDays],["Gäste heute","84",Users],["Bestätigt","23",Check],["Freie Tische","7",TableProperties]].map(([label,value,Icon])=><div key={label as string} className="rounded-2xl bg-white p-5 shadow-sm"><Icon size={20} className="text-[#c68a3b]"/><p className="mt-5 text-3xl font-semibold">{value as string}</p><p className="mt-1 text-sm text-[#10261e]/50">{label as string}</p></div>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl bg-white p-6"><div className="flex items-center justify-between"><h2 className="font-display text-2xl">Nächste Gäste</h2><button onClick={()=>setView("Reservierungen")} className="text-sm text-[#a52520]">Alle anzeigen</button></div><div className="mt-5 divide-y divide-[#10261e]/10">{reservations.map(r=><div key={r.time} className="grid grid-cols-[60px_1fr_auto] items-center gap-3 py-4"><strong>{r.time}</strong><div><p>{r.name}</p><p className="text-xs text-[#10261e]/45">{r.guests} Personen · {r.table}</p></div><span className={`rounded-full px-3 py-1 text-xs ${r.status==="Bestätigt"?"bg-[#dce8dc] text-[#315a38]":"bg-[#f7e6bf] text-[#805c16]"}`}>{r.status}</span></div>)}</div></div><div className="rounded-2xl bg-[#10261e] p-6 text-[#f5e8d3]"><h2 className="font-display text-2xl">Aktivität</h2><div className="mt-6 space-y-5 text-sm">{["Neue Reservierung · Schneider","Tisch 08 bestätigt","Preis für Mole Poblano aktualisiert","Reservierung Weber geändert"].map((x,i)=><div key={x} className="flex gap-3"><span className="mt-2 h-2 w-2 rounded-full bg-[#c68a3b]"/><div><p>{x}</p><p className="text-xs text-white/40">vor {4+i*7} Minuten</p></div></div>)}</div></div></div></>}
  {view==="Reservierungen"&&<div className="mt-8 overflow-hidden rounded-2xl bg-white"><div className="flex flex-wrap items-center justify-between gap-4 border-b p-5"><div className="flex items-center gap-2 rounded-full bg-[#f4f0e8] px-4 py-2"><Search size={17}/><input aria-label="Reservierungen suchen" placeholder="Name oder Nummer suchen" className="bg-transparent outline-none"/></div><button className="button-primary"><Plus size={17}/> Neue Reservierung</button></div><div className="divide-y">{reservations.map(r=><div key={r.time} className="grid gap-3 p-5 sm:grid-cols-[80px_1fr_120px_120px_auto] sm:items-center"><strong>{r.time}</strong><span>{r.name}</span><span>{r.guests} Gäste</span><span>{r.table}</span><button className="flex items-center justify-end gap-1 text-sm text-[#a52520]">Öffnen <ChevronRight size={16}/></button></div>)}</div></div>}
  {view==="Menü"&&<div className="mt-8 rounded-2xl bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="font-display text-2xl">Gerichte</h2><p className="text-sm text-[#10261e]/50">Preise und Verfügbarkeit verwalten</p></div><button className="button-primary"><Plus size={17}/> Gericht hinzufügen</button></div><div className="mt-6 divide-y">{menu.dishes.map(d=><div key={d.id} className="flex items-center gap-4 py-4"><Image src={d.image} width={64} height={64} alt="" className="h-16 w-16 rounded-xl object-cover"/><div className="min-w-0 flex-1"><p className="font-semibold">{d.name.de}</p><p className="truncate text-sm text-[#10261e]/45">{d.description.de}</p></div><strong>€ {d.price.toFixed(2).replace('.',',')}</strong><span className="rounded-full bg-[#dce8dc] px-3 py-1 text-xs text-[#315a38]">Verfügbar</span><button className="text-sm text-[#a52520]">Bearbeiten</button></div>)}</div></div>}
  {(view==="Tische"||view==="Einstellungen")&&<div className="mt-8 rounded-2xl bg-white p-10 text-center"><TableProperties className="mx-auto text-[#c68a3b]" size={36}/><h2 className="font-display mt-4 text-3xl">{view}</h2><p className="mx-auto mt-2 max-w-lg text-[#10261e]/55">Dieser Bereich ist für die nächste Verwaltungsstufe vorbereitet. Restaurantdaten bleiben dabei strukturiert und sicher verwaltbar.</p></div>}
  </section>
</main>}
