import Image from "next/image";
import { env } from "cloudflare:workers";
import { ArrowDownRight, ArrowRight, Clock3, MapPin, Play, Star } from "lucide-react";
import { getMarketingContent } from "../lib/marketing-content.ts";
import { getOperations } from "../lib/operations-config.ts";
import { SiteHeader } from "../components/site-header";
import { StructuredData } from "../components/structured-data";
import { getSiteUrl } from "../lib/site-url";
import { localized,withLocale,type Locale } from "../lib/i18n";
import type {Metadata} from "next";
import {getSeoContent} from "../lib/seo-content.ts";

export async function generateMetadata():Promise<Metadata>{const {content}=await getSeoContent(env.DB),page=content.pages.home;return{title:page.title.de,description:page.description.de,keywords:content.keywords.de.split(",").map(x=>x.trim()),alternates:{canonical:"/",languages:{de:"/",en:"/en"}},openGraph:{title:page.title.de,description:page.description.de,url:"/",locale:"de_DE"}}}

const schemaDays:Record<string,string>={monday:"Monday",tuesday:"Tuesday",wednesday:"Wednesday",thursday:"Thursday",friday:"Friday",saturday:"Saturday",sunday:"Sunday"};

export async function HomeContent({locale}:{locale:Locale}) {
  const L=(de:string,en:string)=>locale==="en"?en:de;
  const [{content:marketing},{config:operations}]=await Promise.all([getMarketingContent(env.DB),getOperations(env.DB)]),restaurant=operations.restaurant;
  return <main className="overflow-hidden bg-[#09130f] text-[#f5e8d3]">
    <StructuredData data={{"@context":"https://schema.org","@type":"Restaurant","@id":`${getSiteUrl()}#restaurant`,name:restaurant.name,legalName:restaurant.legalName,url:getSiteUrl().toString(),telephone:restaurant.contact.phone,email:restaurant.contact.email,address:{"@type":"PostalAddress",streetAddress:restaurant.contact.address,addressCountry:"DE"},servesCuisine:"Mexican",acceptsReservations:true,menu:getSiteUrl("/menu").toString(),sameAs:Object.values(marketing.social).map(item=>item.url).filter(url=>url!=="#"),openingHoursSpecification:Object.entries(restaurant.openingHours).filter(([,hours])=>hours!=="closed").map(([day,hours])=>{const [opens,closes]=(hours as string).split("-");return{"@type":"OpeningHoursSpecification",dayOfWeek:`https://schema.org/${schemaDays[day]}`,opens,closes}}),potentialAction:{"@type":"ReserveAction",target:getSiteUrl("/reservieren").toString()}}}/>
    <SiteHeader active="Start" locale={locale}/>
    <section className="hero-new relative isolate flex min-h-[calc(100svh-6rem)] items-end">
      <Image src="/table-terrace.webp" fill priority alt="Terrasse bei Bailamos am Abend" className="object-cover object-center"/>
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(5,13,10,.95)_0%,rgba(5,13,10,.76)_38%,rgba(5,13,10,.16)_76%,rgba(5,13,10,.52)_100%)]"/>
      <div className="absolute inset-x-0 bottom-0 h-2/5 bg-gradient-to-t from-[#09130f] to-transparent"/>
      <div className="relative mx-auto grid w-full max-w-[1440px] gap-10 px-5 pb-10 pt-24 sm:px-10 lg:grid-cols-[1.2fr_.8fr] lg:px-16 lg:pb-14">
        <div className="self-end pb-4">
          <p className="mb-6 flex items-center gap-3 text-xs font-semibold uppercase tracking-[.24em] text-[#efc67e]"><span className="h-px w-10 bg-[#efc67e]"/>{L("Mexikanisches Restaurant · Berlin","Mexican restaurant · Berlin")}</p>
          <h1 className="font-display max-w-3xl text-[clamp(4.2rem,8vw,8.6rem)] leading-[.79] tracking-[-.06em]">{L("Eine Nacht,","A night")}<br/><em className="font-light text-[#efc67e]">{L("die bleibt.","to remember.")}</em></h1>
          <p className="mt-8 max-w-xl text-lg leading-8 text-white/70">{L("Feuer, frische Aromen und Cocktails mit Charakter. Für lange Gespräche, große Momente und alles dazwischen.","Fire, fresh flavours and cocktails with character. For long conversations, big moments and everything in between.")}</p>
          <div className="mt-9 flex flex-wrap gap-4"><a href={withLocale("/reservieren",locale)} className="button-primary">{L("Tisch reservieren","Reserve a table")} <ArrowRight size={18}/></a><a href={withLocale("/menu",locale)} className="button-glass">{L("Speisekarte","Menu")} <ArrowDownRight size={18}/></a></div>
          <div className="mt-12 flex flex-wrap gap-x-7 gap-y-3 text-sm text-white/60"><span className="flex items-center gap-2"><Clock3 size={16} className="text-[#efc67e]"/>{L("Aktuelle Zeiten im Kontaktbereich","Current hours in the contact section")}</span><span className="flex items-center gap-2"><MapPin size={16} className="text-[#efc67e]"/>{restaurant.contact.address}</span></div>
        </div>
        <aside className="self-end rounded-[1.5rem] border border-white/15 bg-[#0a1812]/80 p-5 backdrop-blur-md sm:p-6">
          <p className="text-xs font-semibold uppercase tracking-[.18em] text-[#efc67e]">{L("Heute bei Bailamos","Today at Bailamos")}</p>
          <h2 className="font-display mt-3 text-3xl">{L("Ein Tisch, der zu Ihnen passt.","A table that suits you.")}</h2>
          <p className="mt-3 text-sm leading-6 text-white/60">{L("Wählen Sie Termin und Gästezahl — dann zeigen wir Ihnen passende Plätze mit Bildern.","Choose a date and party size and we will show you suitable tables with photos.")}</p>
          <a href={withLocale("/reservieren",locale)} className="mt-6 flex items-center justify-between rounded-full bg-[#f5e8d3] px-5 py-4 text-sm font-semibold text-[#10261e]">{L("Verfügbarkeit prüfen","Check availability")} <ArrowRight size={18}/></a>
        </aside>
      </div>
    </section>
    <section id="story" className="relative scroll-mt-24 bg-[#f4ead8] px-5 py-24 text-[#10261e] sm:px-10 lg:py-32">
      <div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-end">
        <div><p className="eyebrow">{L("Die Bailamos Art","The Bailamos way")}</p><h2 className="font-display mt-4 max-w-xl text-5xl leading-[.92] sm:text-7xl">{L("Kein gewöhnlicher Abendessen-Termin.","Not your ordinary dinner date.")}</h2></div>
        <p className="max-w-2xl text-lg leading-8 text-[#10261e]/65">{L("Unsere Küche verbindet das Vertraute mit dem Unerwarteten. Die Musik ist warm, die Drinks sind klar, die Tische laden zum Bleiben ein.","Our kitchen brings the familiar together with the unexpected. Warm music, confident drinks and tables made for staying.")}</p>
      </div>
      <div className="mx-auto mt-14 grid max-w-7xl gap-4 md:grid-cols-[1.25fr_.75fr]">
        <div className="relative aspect-[16/10] overflow-hidden rounded-[2rem]"><Image src="/table-corner.webp" fill alt="Bailamos Interieur bei Kerzenlicht" className="object-cover"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/65 p-7 text-white"><p className="font-display text-3xl">Wärme, die man sieht.</p><p className="mt-1 text-sm text-white/70">Jeder Platz hat seinen eigenen Charakter.</p></div></div>
        <div className="grid gap-4"><div className="rounded-[2rem] bg-[#a52520] p-8 text-[#fff5e5]"><Star className="text-[#efc67e]" size={24}/><p className="font-display mt-12 text-4xl leading-none">Tacos.<br/>Cocktails.<br/>Amigos.</p><a className="mt-8 inline-flex items-center gap-2 text-sm font-semibold" href="/menu">Speisekarte entdecken <ArrowRight size={16}/></a></div><div className="relative min-h-64 overflow-hidden rounded-[2rem]"><Image src="/table-window.webp" fill alt="Fensterplatz bei Bailamos" className="object-cover"/></div></div>
      </div>
    </section>
    <section className="bg-[#10261e] px-5 py-24 sm:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">{L("Aktuell bei Bailamos","Now at Bailamos")}</p><h2 className="font-display mt-3 text-5xl">{L("Abende mit Charakter.","Evenings with character.")}</h2></div><a href={withLocale("/events",locale)} className="button-glass">{L("Alle Events","All events")} <ArrowRight size={17}/></a></div><div className="mt-10 grid gap-5 md:grid-cols-2">{marketing.events.map(event=><a href={withLocale("/events",locale)} key={event.id} className="group overflow-hidden rounded-[1.5rem] border border-white/10 bg-white/5"><div className="relative aspect-[16/8] overflow-hidden"><Image src={event.image} alt={localized(event.title,locale)} fill className="object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-[#09130f]/80 to-transparent"/></div><div className="p-6"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#efc67e]">{new Date(event.date).toLocaleDateString(locale==="en"?"en-GB":"de-DE",{day:"2-digit",month:"long"})} · {event.time}{locale==="de"?" Uhr":""}</p><h3 className="font-display mt-3 text-3xl">{localized(event.title,locale)}</h3><p className="mt-3 leading-6 text-sm text-white/60">{localized(event.summary,locale)}</p></div></a>)}</div></div></section>
    <section id="atmosphere" className="bg-[#f4ead8] px-5 py-24 text-[#10261e] sm:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow">Bailamos Moments</p><h2 className="font-display mt-3 text-5xl leading-none sm:text-6xl">{L("Mehr als ein Abendessen.","More than dinner.")}</h2></div><p className="max-w-md leading-7 text-[#10261e]/60">{L("Kurze Momente aus Küche, Bar und dem Haus. Die Clips öffnen als externe Beispiele.","Moments from our kitchen, bar and dining room. These clips open as external examples.")}</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{marketing.demoMedia.videos.map((video)=><a href={video.url} target="_blank" rel="noreferrer" key={video.url} className="group relative aspect-[4/5] overflow-hidden rounded-[1.75rem] bg-[#10261e]"><img src={video.poster} alt={localized(video.title,locale)} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 to-transparent"/><span className="absolute left-5 top-5 rounded-full bg-white/15 px-3 py-1 text-xs font-semibold text-white backdrop-blur">{L("BEISPIELCLIP","SAMPLE CLIP")} · {video.source}</span><div className="absolute bottom-5 left-5 right-5 flex items-end justify-between text-white"><p className="font-display text-2xl">{localized(video.title,locale)}</p><span aria-label={L("Video ansehen","Watch video")} className="grid h-12 w-12 place-items-center rounded-full bg-[#f5e8d3] text-[#10261e]"><Play size={17} fill="currentColor"/></span></div></a>)}</div><p className="mt-5 text-xs leading-5 text-[#10261e]/55">{localized(marketing.demoMedia.notice,locale)}</p></div></section>
    <section className="overflow-hidden bg-[#a52520] px-5 py-16 sm:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-[#f4c878]">{marketing.social.instagram.handle}</p><h2 className="font-display mt-3 text-5xl text-[#fff4e3]">{L("Aus unserem Alltag.","From our everyday life.")}</h2></div><a href={marketing.social.instagram.url} target="_blank" rel="noreferrer" className="button-glass">{L("Instagram entdecken","Discover Instagram")} <ArrowRight size={17}/></a></div><div className="story-rail mt-9 flex gap-4 overflow-x-auto pb-3">{marketing.demoMedia.gallery.map((item)=><a href={item.url} target="_blank" rel="noreferrer" key={item.image} className="group shrink-0"><div className="relative h-40 w-28 overflow-hidden rounded-[1.35rem] border-2 border-[#f4c878] p-1"><img src={item.image} alt={localized(item.label,locale)} className="h-full w-full rounded-[1.1rem] object-cover"/></div><p className="mt-3 text-center text-sm font-semibold text-[#fff4e3]">{localized(item.label,locale)}</p></a>)}</div><p className="mt-2 text-xs text-[#fff4e3]/65">{localized(marketing.demoMedia.notice,locale)}</p></div></section>
    <section id="contact" className="bg-[#09130f] px-5 py-16 sm:px-10"><div className="mx-auto grid max-w-7xl gap-8 border-y border-[#c68a3b]/25 py-12 md:grid-cols-3"><div><p className="eyebrow">{restaurant.name}</p><p className="font-display mt-3 text-3xl">{restaurant.contact.address}</p></div><div><p className="eyebrow">Öffnungszeiten</p><div className="mt-3 grid grid-cols-[auto_1fr] gap-x-4 text-sm leading-7 text-white/65">{[["Mo",restaurant.openingHours.monday],["Di",restaurant.openingHours.tuesday],["Mi",restaurant.openingHours.wednesday],["Do",restaurant.openingHours.thursday],["Fr",restaurant.openingHours.friday],["Sa",restaurant.openingHours.saturday],["So",restaurant.openingHours.sunday]].map(([day,hours])=><><span key={`${day}-day`}>{day}</span><span key={`${day}-hours`}>{hours==="closed"?"geschlossen":hours.replace("-","–")+" Uhr"}</span></>)}</div></div><div><p className="eyebrow">Reservierungen</p><p className="mt-3 leading-7 text-white/65">{restaurant.contact.phone}<br/>{restaurant.contact.email}</p></div></div><footer className="mx-auto flex max-w-7xl flex-wrap justify-between gap-4 pt-8 text-sm text-white/40"><span>© 2026 {restaurant.name}</span><span>Authentisch · Leidenschaftlich · Mexikanisch</span></footer></section>
  </main>
}
export default function Home(){return <HomeContent locale="de"/>}
