import Image from "next/image";
import { ArrowDownRight, ArrowRight, Clock3, MapPin, Play, Star } from "lucide-react";
import marketing from "../data/marketing.json";
import { SiteHeader } from "../components/site-header";

export default function Home() {
  return <main className="overflow-hidden bg-[#09130f] text-[#f5e8d3]">
    <SiteHeader active="Start"/>
    <section className="hero-new relative isolate flex min-h-[calc(100svh-6rem)] items-end">
      <Image src="/table-terrace.png" fill priority alt="Terrasse bei Bailamos am Abend" className="object-cover object-center"/>
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(5,13,10,.95)_0%,rgba(5,13,10,.76)_38%,rgba(5,13,10,.16)_76%,rgba(5,13,10,.52)_100%)]"/>
      <div className="absolute inset-x-0 bottom-0 h-2/5 bg-gradient-to-t from-[#09130f] to-transparent"/>
      <div className="relative mx-auto grid w-full max-w-[1440px] gap-10 px-5 pb-10 pt-24 sm:px-10 lg:grid-cols-[1.2fr_.8fr] lg:px-16 lg:pb-14">
        <div className="self-end pb-4">
          <p className="mb-6 flex items-center gap-3 text-xs font-semibold uppercase tracking-[.24em] text-[#efc67e]"><span className="h-px w-10 bg-[#efc67e]"/>Mexikanisches Restaurant · Berlin</p>
          <h1 className="font-display max-w-3xl text-[clamp(4.2rem,8vw,8.6rem)] leading-[.79] tracking-[-.06em]">Eine Nacht,<br/><em className="font-light text-[#efc67e]">die bleibt.</em></h1>
          <p className="mt-8 max-w-xl text-lg leading-8 text-white/70">Feuer, frische Aromen und Cocktails mit Charakter. Für lange Gespräche, große Momente und alles dazwischen.</p>
          <div className="mt-9 flex flex-wrap gap-4"><a href="/reservieren" className="button-primary">Tisch reservieren <ArrowRight size={18}/></a><a href="/menu" className="button-glass">Speisekarte <ArrowDownRight size={18}/></a></div>
          <div className="mt-12 flex flex-wrap gap-x-7 gap-y-3 text-sm text-white/60"><span className="flex items-center gap-2"><Clock3 size={16} className="text-[#efc67e]"/>Di–So · ab 17:00 Uhr</span><span className="flex items-center gap-2"><MapPin size={16} className="text-[#efc67e]"/>Berlin-Mitte</span></div>
        </div>
        <aside className="self-end rounded-[1.5rem] border border-white/15 bg-[#0a1812]/80 p-5 backdrop-blur-md sm:p-6">
          <p className="text-xs font-semibold uppercase tracking-[.18em] text-[#efc67e]">Heute bei Bailamos</p>
          <h2 className="font-display mt-3 text-3xl">Ein Tisch, der zu Ihnen passt.</h2>
          <p className="mt-3 text-sm leading-6 text-white/60">Wählen Sie Termin und Gästezahl — dann zeigen wir Ihnen passende Plätze mit Bildern.</p>
          <a href="/reservieren" className="mt-6 flex items-center justify-between rounded-full bg-[#f5e8d3] px-5 py-4 text-sm font-semibold text-[#10261e]">Verfügbarkeit prüfen <ArrowRight size={18}/></a>
        </aside>
      </div>
    </section>
    <section className="relative bg-[#f4ead8] px-5 py-24 text-[#10261e] sm:px-10 lg:py-32">
      <div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-end">
        <div><p className="eyebrow">Die Bailamos Art</p><h2 className="font-display mt-4 max-w-xl text-5xl leading-[.92] sm:text-7xl">Kein gewöhnlicher Abendessen-Termin.</h2></div>
        <p className="max-w-2xl text-lg leading-8 text-[#10261e]/65">Unsere Küche verbindet das Vertraute mit dem Unerwarteten. Die Musik ist warm, die Drinks sind klar, die Tische laden zum Bleiben ein.</p>
      </div>
      <div className="mx-auto mt-14 grid max-w-7xl gap-4 md:grid-cols-[1.25fr_.75fr]">
        <div className="relative aspect-[16/10] overflow-hidden rounded-[2rem]"><Image src="/table-corner.png" fill alt="Bailamos Interieur bei Kerzenlicht" className="object-cover"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/65 p-7 text-white"><p className="font-display text-3xl">Wärme, die man sieht.</p><p className="mt-1 text-sm text-white/70">Jeder Platz hat seinen eigenen Charakter.</p></div></div>
        <div className="grid gap-4"><div className="rounded-[2rem] bg-[#a52520] p-8 text-[#fff5e5]"><Star className="text-[#efc67e]" size={24}/><p className="font-display mt-12 text-4xl leading-none">Tacos.<br/>Cocktails.<br/>Amigos.</p><a className="mt-8 inline-flex items-center gap-2 text-sm font-semibold" href="/menu">Speisekarte entdecken <ArrowRight size={16}/></a></div><div className="relative min-h-64 overflow-hidden rounded-[2rem]"><Image src="/table-window.png" fill alt="Fensterplatz bei Bailamos" className="object-cover"/></div></div>
      </div>
    </section>
    <section className="bg-[#10261e] px-5 py-24 sm:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Aktuell bei Bailamos</p><h2 className="font-display mt-3 text-5xl">Abende mit Charakter.</h2></div><a href="/events" className="button-glass">Alle Events <ArrowRight size={17}/></a></div><div className="mt-10 grid gap-5 md:grid-cols-2">{marketing.events.map(event=><a href="/events" key={event.id} className="group overflow-hidden rounded-[1.5rem] border border-white/10 bg-white/5"><div className="relative aspect-[16/8] overflow-hidden"><Image src={event.image} alt={event.title.de} fill className="object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-[#09130f]/80 to-transparent"/></div><div className="p-6"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#efc67e]">{new Date(event.date).toLocaleDateString("de-DE",{day:"2-digit",month:"long"})} · {event.time} Uhr</p><h3 className="font-display mt-3 text-3xl">{event.title.de}</h3><p className="mt-3 leading-6 text-sm text-white/60">{event.summary.de}</p></div></a>)}</div></div></section>
    <section id="atmosphere" className="bg-[#f4ead8] px-5 py-24 text-[#10261e] sm:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow">Bailamos Moments</p><h2 className="font-display mt-3 text-5xl leading-none sm:text-6xl">Mehr als ein Abendessen.</h2></div><p className="max-w-md leading-7 text-[#10261e]/60">Kurze Momente aus Küche, Bar und dem Haus. Die Clips öffnen als externe Beispiele.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{marketing.demoMedia.videos.map((video)=><a href={video.url} target="_blank" rel="noreferrer" key={video.title} className="group relative aspect-[4/5] overflow-hidden rounded-[1.75rem] bg-[#10261e]"><img src={video.poster} alt={`${video.title} – Beispielvideo`} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 to-transparent"/><span className="absolute left-5 top-5 rounded-full bg-white/15 px-3 py-1 text-xs font-semibold text-white backdrop-blur">BEISPIELCLIP · {video.source}</span><div className="absolute bottom-5 left-5 right-5 flex items-end justify-between text-white"><p className="font-display text-2xl">{video.title}</p><span aria-label={`${video.title} ansehen`} className="grid h-12 w-12 place-items-center rounded-full bg-[#f5e8d3] text-[#10261e]"><Play size={17} fill="currentColor"/></span></div></a>)}</div><p className="mt-5 text-xs leading-5 text-[#10261e]/55">{marketing.demoMedia.notice}</p></div></section>
    <section className="overflow-hidden bg-[#a52520] px-5 py-16 sm:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-[#f4c878]">@bailamos.berlin</p><h2 className="font-display mt-3 text-5xl text-[#fff4e3]">Aus unserem Alltag.</h2></div><a href={marketing.social.instagram.url} className="button-glass">Instagram entdecken <ArrowRight size={17}/></a></div><div className="story-rail mt-9 flex gap-4 overflow-x-auto pb-3">{marketing.demoMedia.gallery.map((item)=><a href={item.url} target="_blank" rel="noreferrer" key={item.label} className="group shrink-0"><div className="relative h-40 w-28 overflow-hidden rounded-[1.35rem] border-2 border-[#f4c878] p-1"><img src={item.image} alt={`${item.label} – Beispielbild`} className="h-full w-full rounded-[1.1rem] object-cover"/></div><p className="mt-3 text-center text-sm font-semibold text-[#fff4e3]">{item.label}</p></a>)}</div><p className="mt-2 text-xs text-[#fff4e3]/65">Beispielbilder · Pexels</p></div></section>
    <section id="contact" className="bg-[#09130f] px-5 py-16 sm:px-10"><div className="mx-auto grid max-w-7xl gap-8 border-y border-[#c68a3b]/25 py-12 md:grid-cols-3"><div><p className="eyebrow">Bailamos Berlin</p><p className="font-display mt-3 text-3xl">Musterstraße 18<br/>10117 Berlin</p></div><div><p className="eyebrow">Öffnungszeiten</p><p className="mt-3 leading-7 text-white/65">Di–Do · 17–23 Uhr<br/>Fr–Sa · 17–01 Uhr<br/>So · 17–22 Uhr</p></div><div><p className="eyebrow">Reservierungen</p><p className="mt-3 leading-7 text-white/65">+49 30 123 45 678<br/>hola@bailamos.berlin</p></div></div><footer className="mx-auto flex max-w-7xl flex-wrap justify-between gap-4 pt-8 text-sm text-white/40"><span>© 2026 Bailamos</span><span>Authentisch · Leidenschaftlich · Mexikanisch</span></footer></section>
  </main>
}
