"use client";
import { useEffect, useState } from "react";
import { CalendarDays, Film, ImagePlus, Languages, Loader2, Plus, Save, Trash2 } from "lucide-react";
import type { MarketingContent } from "../lib/marketing-content";

export function AdminContent({adminKey}:{adminKey:string}){
  const [content,setContent]=useState<MarketingContent|null>(null),[version,setVersion]=useState(0),[language,setLanguage]=useState<"de"|"en">("de"),[aiConfigured,setAiConfigured]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[translating,setTranslating]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  async function request(url:string,options:RequestInit={}):Promise<any>{const response=await fetch(url,{...options,headers:{...options.headers,"x-admin-key":adminKey}}),result=await response.json() as any;if(!response.ok)throw new Error(result.error||"Änderung fehlgeschlagen.");return result}
  async function load(){setLoading(true);setError("");try{const result=await request("/api/admin/content");setContent(result.content);setVersion(result.version);setAiConfigured(result.aiConfigured===true)}catch(cause){setError(cause instanceof Error?cause.message:"Inhalte konnten nicht geladen werden.")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  function change(mutator:(copy:MarketingContent)=>void){if(!content)return;const copy=structuredClone(content);mutator(copy);setContent(copy);setNotice("")}
  async function save(){if(!content)return;setSaving(true);setError("");setNotice("");try{const result=await request("/api/admin/content",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({content,version})});setContent(result.content);setVersion(result.version);setNotice("Änderungen veröffentlicht.")}catch(cause){setError(cause instanceof Error?cause.message:"Änderungen konnten nicht gespeichert werden.")}finally{setSaving(false)}}
  async function upload(file:File){setUploading(true);setError("");try{const result=await request("/api/admin/media",{method:"POST",headers:{"content-type":file.type},body:file}),name=file.name.replace(/\.[^.]+$/,"")||"Bailamos";if(result.kind==="image")change(copy=>copy.demoMedia.gallery.push({label:{de:name,en:name},source:"Bailamos",url:result.url,image:result.url}));else change(copy=>copy.demoMedia.videos.push({title:{de:name,en:name},source:"Bailamos",url:result.url,poster:"/table-terrace.webp"}));setNotice("Datei hochgeladen. Bitte jetzt Änderungen veröffentlichen.")}catch(cause){setError(cause instanceof Error?cause.message:"Upload fehlgeschlagen.")}finally{setUploading(false)}}
  async function generateEnglish(){if(!content)return;setTranslating(true);setError("");try{const texts=[...content.events.flatMap(x=>[x.title.de,x.summary.de]),...content.demoMedia.gallery.map(x=>x.label.de),...content.demoMedia.videos.map(x=>x.title.de)],result=await request("/api/admin/translate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({texts})});let cursor=0;change(copy=>{for(const event of copy.events){event.title.en=result.translations[cursor++];event.summary.en=result.translations[cursor++]}for(const item of copy.demoMedia.gallery)item.label.en=result.translations[cursor++];for(const item of copy.demoMedia.videos)item.title.en=result.translations[cursor++]});setLanguage("en");setNotice("Englischer Entwurf erstellt. Bitte prüfen und veröffentlichen.")}catch(cause){setError(cause instanceof Error?cause.message:"Übersetzung fehlgeschlagen.")}finally{setTranslating(false)}}
  if(loading)return <div className="grid min-h-[480px] place-items-center"><Loader2 className="animate-spin text-[#b8782e]" size={32}/></div>;
  if(!content)return <div className="mx-auto max-w-xl p-10 text-center"><p>{error||"Keine Inhalte verfügbar."}</p><button onClick={load} className="mt-4 text-[#a52520] underline">Erneut versuchen</button></div>;
  return <div className="mx-auto max-w-7xl px-4 py-7 sm:px-8 lg:py-10">
    <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="eyebrow">Website verwalten</p><h1 className="font-display mt-2 text-4xl sm:text-5xl">Content & Marketing</h1><p className="mt-2 text-base text-[#10261e]/55">Deutsch pflegen, Englisch prüfen und gemeinsam veröffentlichen.</p></div><div className="flex flex-wrap gap-3"><div className="flex rounded-full border bg-white p-1">{(["de","en"] as const).map(code=><button key={code} onClick={()=>setLanguage(code)} className={`rounded-full px-4 py-2 text-sm font-semibold ${language===code?"bg-[#10261e] text-white":""}`}>{code.toUpperCase()}</button>)}</div><button disabled={translating||!aiConfigured} onClick={generateEnglish} className="button-secondary disabled:opacity-45" title={aiConfigured?"":"OPENAI_API_KEY noch nicht eingerichtet"}>{translating?<Loader2 className="animate-spin" size={18}/>:<Languages size={18}/>}Englisch generieren</button><button disabled={saving} onClick={save} className="button-primary"><Save size={18}/>{saving?"Wird veröffentlicht…":"Beide Sprachen veröffentlichen"}</button></div></div>
    {(error||notice)&&<p role={error?"alert":"status"} className={`mt-6 rounded-xl p-4 ${error?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-800"}`}>{error||notice}</p>}
    <div className="mt-7 grid gap-6 xl:grid-cols-[1.2fr_.8fr]">
      <section className="rounded-[2rem] bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center justify-between gap-4"><div><h2 className="font-display text-3xl">Events</h2><p className="mt-1 text-sm text-[#10261e]/50">Nur veröffentlichte Events erscheinen auf der Website.</p></div><button onClick={()=>change(copy=>copy.events.unshift({id:`event-${Date.now()}`,title:{de:"Neues Event",en:"New event"},summary:{de:"Beschreibung ergänzen",en:"Add description"},date:new Date().toISOString().slice(0,10),time:"19:00",image:"/table-corner.webp",featured:false,published:false}))} className="inline-flex min-h-11 items-center gap-2 rounded-full bg-[#10261e] px-4 text-sm font-semibold text-white"><Plus size={17}/> Event</button></div>
        <div className="mt-6 space-y-5">{content.events.map((event,index)=><article key={event.id} className="rounded-2xl border border-[#10261e]/10 p-5"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-2"><CalendarDays size={18} className="text-[#b8782e]"/><strong>Event {index+1} · {language.toUpperCase()}</strong></div><button aria-label="Event löschen" onClick={()=>change(copy=>copy.events.splice(index,1))} className="text-[#a52520]"><Trash2 size={18}/></button></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm">Titel<input value={event.title[language]} onChange={e=>change(copy=>copy.events[index].title[language]=e.target.value)} className="min-h-11 rounded-xl border px-3 text-base"/></label><label className="grid gap-1 text-sm">Interne ID<input value={event.id} onChange={e=>change(copy=>copy.events[index].id=e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"-"))} className="min-h-11 rounded-xl border px-3 text-base"/></label><label className="grid gap-1 text-sm">Datum<input type="date" value={event.date} onChange={e=>change(copy=>copy.events[index].date=e.target.value)} className="min-h-11 rounded-xl border px-3 text-base"/></label><label className="grid gap-1 text-sm">Uhrzeit<input type="time" value={event.time} onChange={e=>change(copy=>copy.events[index].time=e.target.value)} className="min-h-11 rounded-xl border px-3 text-base"/></label><label className="grid gap-1 text-sm sm:col-span-2">Beschreibung<textarea rows={3} value={event.summary[language]} onChange={e=>change(copy=>copy.events[index].summary[language]=e.target.value)} className="rounded-xl border px-3 py-2 text-base"/></label><label className="grid gap-1 text-sm sm:col-span-2">Bildadresse<input value={event.image} onChange={e=>change(copy=>copy.events[index].image=e.target.value)} className="min-h-11 rounded-xl border px-3 text-base"/></label></div><label className="mt-4 flex items-center gap-3 text-sm"><input type="checkbox" checked={event.published} onChange={e=>change(copy=>copy.events[index].published=e.target.checked)} className="h-5 w-5"/>Auf der Website veröffentlichen</label></article>)}</div>
      </section>
      <div className="space-y-6">
        <section className="rounded-[2rem] bg-white p-5 shadow-sm sm:p-7"><h2 className="font-display text-3xl">Social Media</h2><div className="mt-5 space-y-4">{(["instagram","facebook","tiktok"] as const).map(network=><div key={network} className="rounded-xl bg-[#f4f0e8] p-4"><label className="grid gap-1 text-sm capitalize">{network} Name<input value={content.social[network].handle} onChange={e=>change(copy=>copy.social[network].handle=e.target.value)} className="min-h-11 rounded-xl border bg-white px-3 text-base"/></label><label className="mt-3 grid gap-1 text-sm">Profil-Link<input type="url" placeholder="https://…" value={content.social[network].url==="#"?"":content.social[network].url} onChange={e=>change(copy=>copy.social[network].url=e.target.value||"#")} className="min-h-11 rounded-xl border bg-white px-3 text-base"/></label></div>)}</div></section>
        <section className="rounded-[2rem] bg-[#10261e] p-5 text-[#f5e8d3] shadow-sm sm:p-7"><h2 className="font-display text-3xl">Medien hochladen</h2><p className="mt-2 text-sm leading-6 text-white/55">JPG, PNG, WebP, MP4 oder WebM · maximal 50 MB. Neue Bilder landen in der Galerie, Videos im Videobereich.</p><label className="mt-5 flex min-h-14 cursor-pointer items-center justify-center gap-2 rounded-full border border-[#c68a3b]/50 text-sm font-semibold hover:bg-white/5">{uploading?<Loader2 className="animate-spin" size={18}/>:<ImagePlus size={18}/>} {uploading?"Wird hochgeladen…":"Bild oder Video wählen"}<input disabled={uploading} type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" className="sr-only" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value=""}}/></label></section>
        <section className="rounded-[2rem] bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center gap-2"><ImagePlus size={18} className="text-[#b8782e]"/><h2 className="font-display text-3xl">Galerie · {language.toUpperCase()}</h2></div><div className="mt-5 space-y-3">{content.demoMedia.gallery.map((item,index)=><div key={`${item.image}-${index}`} className="flex items-center gap-3 rounded-xl border p-3"><img src={item.image} alt="" className="h-14 w-14 rounded-lg object-cover"/><input aria-label="Bildtitel" value={item.label[language]} onChange={e=>change(copy=>copy.demoMedia.gallery[index].label[language]=e.target.value)} className="min-w-0 flex-1 border-b bg-transparent py-2"/><button aria-label="Bild entfernen" onClick={()=>change(copy=>copy.demoMedia.gallery.splice(index,1))} className="text-[#a52520]"><Trash2 size={17}/></button></div>)}</div></section>
        <section className="rounded-[2rem] bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center gap-2"><Film size={18} className="text-[#b8782e]"/><h2 className="font-display text-3xl">Videos · {language.toUpperCase()}</h2></div><div className="mt-5 space-y-3">{content.demoMedia.videos.map((item,index)=><div key={`${item.url}-${index}`} className="rounded-xl border p-4"><div className="flex items-center gap-3"><input aria-label="Videotitel" value={item.title[language]} onChange={e=>change(copy=>copy.demoMedia.videos[index].title[language]=e.target.value)} className="min-w-0 flex-1 border-b py-2 font-semibold"/><button aria-label="Video entfernen" onClick={()=>change(copy=>copy.demoMedia.videos.splice(index,1))} className="text-[#a52520]"><Trash2 size={17}/></button></div><input aria-label="Videoadresse" value={item.url} onChange={e=>change(copy=>copy.demoMedia.videos[index].url=e.target.value)} className="mt-3 w-full border-b py-2 text-sm"/></div>)}</div></section>
      </div>
    </div>
  </div>
}
