"use client";
import { useEffect,useMemo,useState } from "react";
import { ImagePlus,Loader2,Plus,Save,Search,Trash2,UtensilsCrossed } from "lucide-react";
import type { MenuContent } from "../lib/menu-content";

export function AdminMenu({adminKey}:{adminKey:string}){
 const [menu,setMenu]=useState<MenuContent|null>(null),[version,setVersion]=useState(0),[selected,setSelected]=useState(""),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function request(url:string,options:RequestInit={}):Promise<any>{const response=await fetch(url,{...options,headers:{...options.headers,"x-admin-key":adminKey}}),result=await response.json() as any;if(!response.ok)throw new Error(result.error||"Änderung fehlgeschlagen.");return result}
 async function load(){setLoading(true);setError("");try{const result=await request("/api/admin/menu");setMenu(result.content);setVersion(result.version);setSelected(result.content.dishes[0]?.id||"")}catch(cause){setError(cause instanceof Error?cause.message:"Speisekarte konnte nicht geladen werden.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 function change(mutator:(copy:MenuContent)=>void){if(!menu)return;const copy=structuredClone(menu);mutator(copy);setMenu(copy);setNotice("")}
 async function save(){if(!menu)return;setSaving(true);setError("");setNotice("");try{const result=await request("/api/admin/menu",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({content:menu,version})});setMenu(result.content);setVersion(result.version);setNotice("Speisekarte veröffentlicht.")}catch(cause){setError(cause instanceof Error?cause.message:"Speisekarte konnte nicht gespeichert werden.")}finally{setSaving(false)}}
 async function upload(file:File){if(!dish)return;setUploading(true);setError("");try{const result=await request("/api/admin/media",{method:"POST",headers:{"content-type":file.type},body:file});if(result.kind!=="image")throw new Error("Bitte ein Bild auswählen.");change(copy=>{const item=copy.dishes.find(value=>value.id===selected);if(item)item.image=result.url});setNotice("Foto hochgeladen. Bitte Speisekarte veröffentlichen.")}catch(cause){setError(cause instanceof Error?cause.message:"Upload fehlgeschlagen.")}finally{setUploading(false)}}
 const shown=useMemo(()=>menu?.dishes.filter(item=>`${item.name.de} ${item.categoryId}`.toLowerCase().includes(query.toLowerCase()))||[],[menu,query]);
 const dish=menu?.dishes.find(item=>item.id===selected);
 if(loading)return <div className="grid min-h-[480px] place-items-center"><Loader2 className="animate-spin text-[#b8782e]" size={32}/></div>;
 if(!menu)return <div className="p-10 text-center"><p>{error}</p><button onClick={load} className="mt-4 text-[#a52520] underline">Erneut versuchen</button></div>;
 function addDish(){const categoryId=menu!.categories[0].id,id=`gericht-${Date.now()}`;change(copy=>copy.dishes.unshift({id,categoryId,name:{de:"Neues Gericht",en:"New dish"},description:{de:"Beschreibung ergänzen",en:"Add description"},price:0,image:"/table-corner.webp",featured:false,available:false,vegetarian:false,spicy:0,allergens:[]}));setSelected(id)}
 function addCategory(){const id=`kategorie-${Date.now()}`;change(copy=>copy.categories.push({id,name:{de:"Neue Kategorie",en:"New category"}}))}
 function removeCategory(id:string){if(menu!.dishes.some(item=>item.categoryId===id)){setError("Verschieben oder löschen Sie zuerst die Gerichte dieser Kategorie.");return}if(menu!.categories.length===1){setError("Mindestens eine Kategorie muss bestehen bleiben.");return}change(copy=>{const index=copy.categories.findIndex(item=>item.id===id);copy.categories.splice(index,1)})}
 return <div className="mx-auto max-w-7xl px-4 py-7 sm:px-8 lg:py-10"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Website verwalten</p><h1 className="font-display mt-2 text-4xl sm:text-5xl">Speisekarte</h1><p className="mt-2 text-base text-[#10261e]/55">Gerichte, Preise, Allergene und Verfügbarkeit.</p></div><button disabled={saving} onClick={save} className="button-primary"><Save size={18}/>{saving?"Wird veröffentlicht…":"Speisekarte veröffentlichen"}</button></div>
 {(error||notice)&&<p role={error?"alert":"status"} className={`mt-6 rounded-xl p-4 ${error?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-800"}`}>{error||notice}</p>}
 <section className="mt-7 rounded-[2rem] bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><h2 className="font-display text-3xl">Kategorien</h2><button onClick={addCategory} className="inline-flex items-center gap-2 text-sm font-semibold text-[#a52520]"><Plus size={17}/> Kategorie</button></div><div className="mt-4 flex gap-3 overflow-x-auto pb-2">{menu.categories.map((category,index)=><div key={category.id} className="flex min-w-[210px] items-center gap-2 rounded-xl bg-[#f4f0e8] p-3"><input aria-label={`Kategorie ${index+1}`} value={category.name.de} onChange={e=>change(copy=>copy.categories[index].name.de=e.target.value)} className="min-w-0 flex-1 bg-transparent font-semibold outline-none"/><button aria-label="Kategorie entfernen" onClick={()=>removeCategory(category.id)} className="text-[#a52520]"><Trash2 size={16}/></button></div>)}</div></section>
 <section className="mt-6 grid min-h-[560px] overflow-hidden rounded-[2rem] bg-white shadow-sm lg:grid-cols-[.72fr_1.28fr]"><div className="border-b lg:border-b-0 lg:border-r"><div className="flex gap-3 border-b p-5"><label className="flex min-h-11 flex-1 items-center gap-2 rounded-xl bg-[#f4f0e8] px-3"><Search size={17}/><input aria-label="Gerichte suchen" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Gericht suchen" className="min-w-0 flex-1 bg-transparent outline-none"/></label><button onClick={addDish} aria-label="Gericht hinzufügen" className="grid h-11 w-11 place-items-center rounded-xl bg-[#10261e] text-white"><Plus size={18}/></button></div><div className="divide-y">{shown.map(item=><button key={item.id} onClick={()=>setSelected(item.id)} className={`flex w-full items-center gap-3 p-4 text-left ${selected===item.id?"bg-[#fff8ec]":"hover:bg-[#f4f0e8]"}`}><img src={item.image} alt="" className="h-14 w-14 rounded-xl object-cover"/><span className="min-w-0 flex-1"><strong className="block truncate">{item.name.de}</strong><span className="mt-1 block text-sm text-[#10261e]/50">€ {item.price.toFixed(2).replace(".",",")} · {item.available?"Verfügbar":"Pausiert"}</span></span></button>)}</div></div>
 <div>{!dish?<div className="grid min-h-[560px] place-items-center p-8 text-center"><div><UtensilsCrossed className="mx-auto text-[#c68a3b]" size={34}/><p className="mt-4">Gericht auswählen oder hinzufügen.</p></div></div>:<article className="p-5 sm:p-8"><div className="flex items-start justify-between gap-5"><div><p className="text-sm text-[#10261e]/45">Gericht bearbeiten</p><h2 className="font-display mt-1 text-4xl">{dish.name.de}</h2></div><button aria-label="Gericht löschen" onClick={()=>{change(copy=>{const index=copy.dishes.findIndex(item=>item.id===dish.id);copy.dishes.splice(index,1)});setSelected("")}} className="grid h-11 w-11 place-items-center rounded-full bg-red-50 text-[#a52520]"><Trash2 size={18}/></button></div>
 <div className="mt-7 grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm">Name<input value={dish.name.de} onChange={e=>change(copy=>copy.dishes.find(item=>item.id===dish.id)!.name.de=e.target.value)} className="min-h-11 rounded-xl border px-3 text-base"/></label><label className="grid gap-1 text-sm">Interne ID<input value={dish.id} onChange={e=>{const value=e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"-");change(copy=>copy.dishes.find(item=>item.id===dish.id)!.id=value);setSelected(value)}} className="min-h-11 rounded-xl border px-3 text-base"/></label><label className="grid gap-1 text-sm">Kategorie<select value={dish.categoryId} onChange={e=>change(copy=>copy.dishes.find(item=>item.id===dish.id)!.categoryId=e.target.value)} className="min-h-11 rounded-xl border px-3 text-base">{menu.categories.map(category=><option key={category.id} value={category.id}>{category.name.de}</option>)}</select></label><label className="grid gap-1 text-sm">Preis in Euro<input type="number" min="0" max="999" step="0.01" value={dish.price} onChange={e=>change(copy=>copy.dishes.find(item=>item.id===dish.id)!.price=Number(e.target.value))} className="min-h-11 rounded-xl border px-3 text-base"/></label><label className="grid gap-1 text-sm sm:col-span-2">Beschreibung<textarea rows={3} value={dish.description.de} onChange={e=>change(copy=>copy.dishes.find(item=>item.id===dish.id)!.description.de=e.target.value)} className="rounded-xl border px-3 py-2 text-base"/></label><label className="grid gap-1 text-sm sm:col-span-2">Allergene, durch Komma getrennt<input value={dish.allergens.join(", ")} onChange={e=>change(copy=>copy.dishes.find(item=>item.id===dish.id)!.allergens=e.target.value.split(",").map(value=>value.trim()).filter(Boolean))} className="min-h-11 rounded-xl border px-3 text-base"/></label><label className="grid gap-1 text-sm">Schärfe<select value={dish.spicy} onChange={e=>change(copy=>copy.dishes.find(item=>item.id===dish.id)!.spicy=Number(e.target.value))} className="min-h-11 rounded-xl border px-3 text-base"><option value={0}>Nicht scharf</option><option value={1}>Leicht</option><option value={2}>Mittel</option><option value={3}>Scharf</option></select></label><div className="flex flex-col justify-end gap-3 pb-1"><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={dish.available} onChange={e=>change(copy=>copy.dishes.find(item=>item.id===dish.id)!.available=e.target.checked)} className="h-5 w-5"/>Auf der Karte verfügbar</label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={dish.vegetarian===true} onChange={e=>change(copy=>copy.dishes.find(item=>item.id===dish.id)!.vegetarian=e.target.checked)} className="h-5 w-5"/>Vegetarisch</label></div></div>
 <div className="mt-6 overflow-hidden rounded-2xl border"><img src={dish.image} alt={dish.name.de} className="aspect-[16/7] w-full object-cover"/><div className="flex flex-wrap items-center gap-3 p-4"><label className="inline-flex min-h-11 cursor-pointer items-center gap-2 rounded-full bg-[#10261e] px-4 text-sm font-semibold text-white">{uploading?<Loader2 className="animate-spin" size={17}/>:<ImagePlus size={17}/>}Foto ersetzen<input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} className="sr-only" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value=""}}/></label><input aria-label="Bildadresse" value={dish.image} onChange={e=>change(copy=>copy.dishes.find(item=>item.id===dish.id)!.image=e.target.value)} className="min-h-11 min-w-0 flex-1 rounded-xl border px-3 text-sm"/></div></div></article>}</div></section></div>
}
