import defaults from "../data/menu.json" with {type:"json"};
import { BookingError } from "./booking-policy.ts";
export type MenuContent={categories:Array<{id:string;name:{de:string;en:string}}>;dishes:Array<{id:string;categoryId:string;name:{de:string;en:string};description:{de:string;en:string};price:number;image:string;featured:boolean;available:boolean;vegetarian?:boolean;spicy:number;allergens:string[]}>};
function text(value:unknown,label:string,max:number){if(typeof value!=="string")throw new BookingError(400,"INVALID_MENU",`${label} fehlt.`);const clean=value.trim().normalize("NFC");if(!clean||clean.length>max)throw new BookingError(400,"INVALID_MENU",`${label} ist ungültig.`);return clean}
function slug(value:unknown,label:string){const clean=text(value,label,80);if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(clean))throw new BookingError(400,"INVALID_MENU",`${label} darf nur Kleinbuchstaben, Zahlen und Bindestriche enthalten.`);return clean}
function image(value:unknown){const clean=text(value,"Bildadresse",1000);if(clean.startsWith("/")&&!clean.startsWith("//"))return clean;try{const parsed=new URL(clean);if(["http:","https:"].includes(parsed.protocol))return clean}catch{}throw new BookingError(400,"INVALID_MENU","Die Bildadresse ist nicht sicher.")}
export function validateMenu(value:unknown):MenuContent{
 if(!value||typeof value!=="object"||Array.isArray(value))throw new BookingError(400,"INVALID_MENU","Ungültige Speisekarte.");const v=value as Record<string,any>;
 if(!Array.isArray(v.categories)||!v.categories.length||v.categories.length>30||!Array.isArray(v.dishes)||v.dishes.length>300)throw new BookingError(400,"INVALID_MENU","Bitte Kategorien und Gerichte prüfen.");
 const categoryIds=new Set<string>(),dishIds=new Set<string>();
 const categories=v.categories.map((category:Record<string,any>)=>{const id=slug(category.id,"Kategorie-ID");if(categoryIds.has(id))throw new BookingError(400,"INVALID_MENU","Kategorie-IDs müssen eindeutig sein.");categoryIds.add(id);return{id,name:{de:text(category.name?.de,"Kategoriename",80),en:text(category.name?.en||category.name?.de,"Englischer Kategoriename",80)}}});
 const dishes=v.dishes.map((dish:Record<string,any>)=>{const id=slug(dish.id,"Gericht-ID"),categoryId=slug(dish.categoryId,"Kategorie");if(dishIds.has(id))throw new BookingError(400,"INVALID_MENU","Gericht-IDs müssen eindeutig sein.");dishIds.add(id);if(!categoryIds.has(categoryId))throw new BookingError(400,"INVALID_MENU","Jedes Gericht benötigt eine vorhandene Kategorie.");const price=Number(dish.price);if(!Number.isFinite(price)||price<0||price>999||Math.abs(price*100-Math.round(price*100))>1e-7)throw new BookingError(400,"INVALID_MENU","Bitte einen gültigen Preis mit höchstens zwei Nachkommastellen eingeben.");if(!Array.isArray(dish.allergens)||dish.allergens.length>30)throw new BookingError(400,"INVALID_MENU","Bitte Allergene prüfen.");return{id,categoryId,name:{de:text(dish.name?.de,"Gerichtname",120),en:text(dish.name?.en||dish.name?.de,"Englischer Gerichtname",120)},description:{de:text(dish.description?.de,"Beschreibung",1200),en:text(dish.description?.en||dish.description?.de,"Englische Beschreibung",1200)},price,image:image(dish.image),featured:dish.featured===true,available:dish.available===true,vegetarian:dish.vegetarian===true,spicy:Math.max(0,Math.min(3,Math.trunc(Number(dish.spicy)||0))),allergens:dish.allergens.map((item:unknown)=>text(item,"Allergen",60))}});
 return{categories,dishes};
}
export async function getMenuContent(db?:D1Database):Promise<{content:MenuContent;version:number;source:"saved"|"default"}>{if(!db)return{content:defaults,version:0,source:"default"};try{const row=await db.prepare("SELECT content_json,version FROM menu_content WHERE id='primary'").first<{content_json:string;version:number}>();if(!row)return{content:defaults,version:0,source:"default"};return{content:validateMenu(JSON.parse(row.content_json)),version:row.version,source:"saved"}}catch(error){console.error("Menu content unavailable",error);return{content:defaults,version:0,source:"default"}}}
export async function saveMenuContent(db:D1Database,value:unknown,expectedVersion:number){const content=validateMenu(value),stamp=new Date().toISOString();if(expectedVersion===0){try{await db.prepare("INSERT INTO menu_content (id,content_json,version,updated_at) VALUES ('primary',?,1,?)").bind(JSON.stringify(content),stamp).run();return{content,version:1}}catch(error){if(!String(error).includes("UNIQUE"))throw error}}const result=await db.prepare("UPDATE menu_content SET content_json=?,version=version+1,updated_at=? WHERE id='primary' AND version=?").bind(JSON.stringify(content),stamp,expectedVersion).run();if(!result.meta.changes)throw new BookingError(409,"STALE_MENU","Die Speisekarte wurde inzwischen geändert. Bitte laden Sie sie neu.");return{content,version:expectedVersion+1}}
