import restaurantDefaults from "../data/restaurant.json" with {type:"json"};
import tableDefaults from "../data/tables.json" with {type:"json"};
import {BookingError,berlinDate} from "./booking-policy.ts";
export type TableConfig={id:string;name:string;capacity:number;area:{de:string;en:string};setting:{de:string;en:string};feature:{de:string;en:string};image:string;enabled:boolean};
export type OperationsConfig={restaurant:typeof restaurantDefaults;tables:TableConfig[];booking:{leadMinutes:number;horizonDays:number}};
export const defaultOperations:OperationsConfig={restaurant:restaurantDefaults,tables:tableDefaults,booking:{leadMinutes:30,horizonDays:180}};
function text(value:unknown,label:string,max:number){if(typeof value!=="string")throw new BookingError(400,"INVALID_CONFIG",`${label} fehlt.`);const clean=value.trim().normalize("NFC");if(!clean||clean.length>max)throw new BookingError(400,"INVALID_CONFIG",`${label} ist ungültig.`);return clean}
function id(value:unknown){const clean=text(value,"Tisch-ID",60);if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(clean))throw new BookingError(400,"INVALID_CONFIG","Tisch-IDs dürfen nur Kleinbuchstaben, Zahlen und Bindestriche enthalten.");return clean}
function integer(value:unknown,label:string,min:number,max:number){if(typeof value!=="number"||!Number.isInteger(value)||value<min||value>max)throw new BookingError(400,"INVALID_CONFIG",`${label} ist ungültig.`);return value}
function contact(value:unknown,label:string){return text(value,label,300)}
function safeImage(value:unknown){const clean=text(value,"Tischbild",1000);if(clean.startsWith("/")&&!clean.startsWith("//"))return clean;try{const parsed=new URL(clean);if(["https:","http:"].includes(parsed.protocol))return clean}catch{}throw new BookingError(400,"INVALID_CONFIG","Die Tischbild-Adresse ist nicht sicher.")}
const days=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"] as const;
function hours(value:unknown){if(value==="closed")return value;if(typeof value!=="string"||!/^([01]\d|2[0-3]):[0-5]\d-([01]\d|2[0-3]):[0-5]\d$/.test(value))throw new BookingError(400,"INVALID_CONFIG","Öffnungszeiten müssen wie 17:00-23:00 eingetragen werden.");return value}
export function validateOperations(value:unknown):OperationsConfig{
 if(!value||typeof value!=="object"||Array.isArray(value))throw new BookingError(400,"INVALID_CONFIG","Ungültige Einstellungen.");const v=value as Record<string,any>,r=v.restaurant||{},booking=v.booking||{};
 if(!Array.isArray(v.tables)||!v.tables.length||v.tables.length>100)throw new BookingError(400,"INVALID_CONFIG","Mindestens ein Tisch ist erforderlich.");const ids=new Set<string>();
 const tables=v.tables.map((table:Record<string,any>)=>{const tableId=id(table.id);if(ids.has(tableId))throw new BookingError(400,"INVALID_CONFIG","Tisch-IDs müssen eindeutig sein.");ids.add(tableId);return{id:tableId,name:text(table.name,"Tischname",80),capacity:integer(table.capacity,"Tischkapazität",1,50),area:{de:text(table.area?.de,"Bereich",80),en:text(table.area?.en||table.area?.de,"Englischer Bereich",80)},setting:{de:text(table.setting?.de,"Platzierung",80),en:text(table.setting?.en||table.setting?.de,"Englische Platzierung",80)},feature:{de:text(table.feature?.de,"Beschreibung",240),en:text(table.feature?.en||table.feature?.de,"Englische Beschreibung",240)},image:safeImage(table.image),enabled:table.enabled===true}});
 const openingHours=Object.fromEntries(days.map(day=>[day,hours(r.openingHours?.[day])])) as typeof restaurantDefaults.openingHours;
 const restaurant={name:text(r.name,"Restaurantname",100),legalName:text(r.legalName||r.name,"Rechtlicher Name",160),languages:["de","en"],contact:{address:contact(r.contact?.address,"Adresse"),phone:contact(r.contact?.phone,"Telefon"),email:contact(r.contact?.email,"E-Mail"),whatsapp:contact(r.contact?.whatsapp||r.contact?.phone,"WhatsApp")},openingHours,reservation:{durationMinutes:integer(r.reservation?.durationMinutes,"Reservierungsdauer",30,360),intervalMinutes:integer(r.reservation?.intervalMinutes,"Zeitintervall",15,120),maximumGuests:integer(r.reservation?.maximumGuests,"Maximale Gästezahl",1,50)},features:{panorama:false,whatsapp:r.features?.whatsapp===true}} as typeof restaurantDefaults;
 if(restaurant.reservation.durationMinutes%restaurant.reservation.intervalMinutes!==0)throw new BookingError(400,"INVALID_CONFIG","Die Reservierungsdauer muss durch das Zeitintervall teilbar sein.");
 return{restaurant,tables,booking:{leadMinutes:integer(booking.leadMinutes,"Vorlaufzeit",0,1440),horizonDays:integer(booking.horizonDays,"Buchungszeitraum",1,730)}};
}
export async function getOperations(db?:D1Database):Promise<{config:OperationsConfig;version:number;source:"saved"|"default"}>{if(!db)return{config:defaultOperations,version:0,source:"default"};try{const row=await db.prepare("SELECT config_json,version FROM operations_config WHERE id='primary'").first<{config_json:string;version:number}>();if(!row)return{config:defaultOperations,version:0,source:"default"};return{config:validateOperations(JSON.parse(row.config_json)),version:row.version,source:"saved"}}catch(error){console.error("Operations config unavailable",error);return{config:defaultOperations,version:0,source:"default"}}}
export async function saveOperations(db:D1Database,value:unknown,expectedVersion:number){const config=validateOperations(value),enabled=new Map(config.tables.filter(table=>table.enabled).map(table=>[table.id,table.capacity]));const rows=await db.prepare("SELECT table_id,MAX(guest_count) AS guests FROM reservations WHERE date >= ? AND status IN ('pending','confirmed','arrived','seated') GROUP BY table_id").bind(berlinDate()).all<{table_id:string;guests:number}>();for(const row of rows.results){const capacity=enabled.get(row.table_id);if(!capacity||capacity<row.guests)throw new BookingError(409,"TABLE_IN_USE",`${row.table_id} kann nicht deaktiviert oder verkleinert werden, weil zukünftige Reservierungen bestehen.`)}const stamp=new Date().toISOString();if(expectedVersion===0){try{await db.prepare("INSERT INTO operations_config(id,config_json,version,updated_at) VALUES('primary',?,1,?)").bind(JSON.stringify(config),stamp).run();return{config,version:1}}catch(error){if(!String(error).includes("UNIQUE"))throw error}}const result=await db.prepare("UPDATE operations_config SET config_json=?,version=version+1,updated_at=? WHERE id='primary' AND version=?").bind(JSON.stringify(config),stamp,expectedVersion).run();if(!result.meta.changes)throw new BookingError(409,"STALE_CONFIG","Die Einstellungen wurden inzwischen geändert. Bitte neu laden.");return{config,version:expectedVersion+1}}
