import Image from "next/image";
import { env } from "cloudflare:workers";
import Link from "next/link";
import { ArrowRight, CalendarDays, Clock3, Share2 } from "lucide-react";
import { getMarketingContent } from "../../lib/marketing-content.ts";
import { SiteHeader } from "../../components/site-header";
import type { Metadata } from "next";
import { getSeoContent } from "../../lib/seo-content.ts";

export async function generateMetadata():Promise<Metadata>{const {content}=await getSeoContent(env.DB),page=content.pages.events;return{title:page.title,description:page.description,alternates:{canonical:"/events"},openGraph:{title:page.title,description:page.description,url:"/events"}}}

export default async function Events(){const {content:marketing}=await getMarketingContent(env.DB);return <main className="min-h-screen bg-[#fff8ec] text-[#10261e]"><SiteHeader active="Events"/><section className="px-5 py-20 text-center"><p className="eyebrow">Was bei uns passiert</p><h1 className="font-display mt-3 text-6xl sm:text-7xl">Aktuelle Events</h1><p className="mx-auto mt-5 max-w-2xl text-[#10261e]/55">Besondere Abende, gemeinsame Tafeln und Geschichten rund um mexikanische Küche und Kultur.</p></section><div className="mx-auto grid max-w-7xl gap-8 px-5 pb-24 sm:px-10 lg:grid-cols-2">{marketing.events.filter(event=>event.published).map(event=><article key={event.id} className="overflow-hidden rounded-2xl bg-white shadow-[0_20px_60px_rgba(16,38,30,.1)]"><div className="relative aspect-[16/10]"><Image src={event.image} fill alt={event.title.de} className="object-cover" sizes="50vw"/></div><div className="p-7"><div className="flex flex-wrap gap-4 text-sm text-[#a52520]"><span className="flex items-center gap-2"><CalendarDays size={17}/>{new Date(event.date).toLocaleDateString('de-DE',{day:'2-digit',month:'long',year:'numeric'})}</span><span className="flex items-center gap-2"><Clock3 size={17}/>{event.time} Uhr</span></div><h2 className="font-display mt-4 text-4xl">{event.title.de}</h2><p className="mt-4 leading-7 text-[#10261e]/60">{event.summary.de}</p><div className="mt-7 flex items-center justify-between"><Link href="/reservieren" className="button-primary">Platz reservieren <ArrowRight size={17}/></Link><button aria-label="Event teilen" className="grid h-12 w-12 place-items-center rounded-full border border-[#10261e]/15"><Share2 size={18}/></button></div></div></article>)}</div></main>}
