import { env } from 'cloudflare:workers';
import { getMarketingContent } from '../../lib/marketing-content.ts';
import { getSiteUrl } from '../../lib/site-url.ts';
import { SocialLink } from '../../components/social-link';
const address={street:'Anton-Saefkow-Allee 2A',postalCode:'14772',city:'Brandenburg an der Havel'},email='info@bailamos-waldcafe.de',mapsUrl='https://www.google.com/maps/search/?api=1&query=Anton-Saefkow-Allee+2A,+14772+Brandenburg+an+der+Havel';
const profiles=[['Instagram','https://www.instagram.com/bailamos_waldcafe/'],['TikTok','https://www.tiktok.com/@bailamos.waldcafe'],['YouTube','https://www.youtube.com/channel/UCOix77VvOuExvfUWhey8sWw'],['Facebook','https://www.facebook.com/people/Bailamos-Mexikanisches-Restaurant-Wald-Caf%C3%A9/61595073784535/']];
export const dynamic='force-dynamic';
const seoTitle='Mexikanisches Restaurant & Cocktailbar in Brandenburg an der Havel – Eröffnung bald',seoDescription='Bailamos – mexikanisches Restaurant & Cocktailbar im Wald Café, Anton-Saefkow-Allee 2A, 14772 Brandenburg an der Havel. Tacos, Margaritas, Mezcal & Musik. Eröffnung demnächst.';
export const metadata={title:seoTitle,description:seoDescription,alternates:{canonical:'/opening'},openGraph:{title:`Bailamos · ${seoTitle}`,description:seoDescription,url:'/opening',type:'website',locale:'de_DE',siteName:'Bailamos',images:['/bailamos-logo.jpg']}};
export default async function OpeningPage({searchParams}:{searchParams:Promise<{lang?:string}>}){
  const [{content},query]=await Promise.all([getMarketingContent(env.DB),searchParams]);const c=content.opening,lang=query.lang==='en'?'en':'de',en=lang==='en';
  const date=c.openingDate?new Intl.DateTimeFormat(en?'en-GB':'de-DE',{day:'numeric',month:'long',year:'numeric',timeZone:'Europe/Berlin'}).format(new Date(c.openingDate+'T12:00:00Z')):en?'Opening soon':'Wir eröffnen bald';
  const structuredData={'@context':'https://schema.org','@type':'Restaurant',name:'Bailamos Waldcafé',description:'Mexikanisches Restaurant & Cocktailbar im Wald Café',servesCuisine:'Mexican',url:getSiteUrl('/').toString(),email,image:getSiteUrl('/bailamos-logo.jpg').toString(),address:{'@type':'PostalAddress',streetAddress:address.street,postalCode:address.postalCode,addressLocality:address.city,addressCountry:'DE'},sameAs:profiles.map(([,url])=>url)};
  return <main lang={lang} className="min-h-screen bg-[#10261e] px-5 py-7 text-[#f8edda] sm:px-10"><div className="mx-auto max-w-6xl"><nav aria-label={en?'Language':'Sprache'} className="flex justify-end gap-5 text-sm"><a aria-current={!en?'page':undefined} href="/opening?lang=de" className={!en?'underline underline-offset-4':''}>DE</a><a aria-current={en?'page':undefined} href="/opening?lang=en" className={en?'underline underline-offset-4':''}>EN</a></nav><div className="grid items-center gap-9 py-12 lg:grid-cols-2 lg:gap-16"><a href="#opening-details" aria-label={en?'Read opening details':'Eröffnungsdetails lesen'} className="block overflow-hidden rounded-2xl border border-[#c89b5c]/40 focus-visible:outline-4 focus-visible:outline-[#efc67e]">{c.image?<img src={c.image} alt="Bailamos · Wald Café" className="max-h-[65vh] w-full object-contain"/>:<span className="block p-16 text-center font-display text-5xl">BAILAMOS</span>}</a><div><p className="text-sm uppercase tracking-[.2em] text-[#efc67e]">Brandenburg an der Havel</p><p className="font-display mt-5 text-5xl sm:text-7xl">BAILAMOS</p><h1 className="font-display mt-6 text-3xl sm:text-4xl">{c.headline[lang]}</h1><p className="mt-5 text-lg leading-8 text-[#f8edda]/80">{c.message[lang]}</p><p className="mt-7 border-t border-[#c89b5c]/30 pt-6 text-2xl text-[#efc67e]">{date}</p><a href="#opening-details" className="mt-7 inline-flex min-h-12 items-center rounded-full border border-[#c89b5c] px-6">{en?'About the opening':'Zur Eröffnung'}</a></div></div><section id="opening-details" className="scroll-mt-8 border-t border-[#c89b5c]/30 py-12"><h2 className="font-display text-3xl">{en?'Welcome to a new chapter':'Willkommen zu einem neuen Kapitel'}</h2><p className="mt-4 max-w-2xl text-base leading-7 text-[#f8edda]/80">{en?'Mexican restaurant & cocktail bar at Wald Café. The full website and online reservations will be available when released.':'Mexikanisches Restaurant & Cocktail Bar im Wald Café. Die vollständige Website und Online-Reservierung stehen nach der Freigabe bereit.'}</p><address className="mt-8 grid gap-2 not-italic text-[#f8edda]/85"><span className="text-sm uppercase tracking-[.2em] text-[#efc67e]">{en?'Address':'Adresse'}</span><a href={mapsUrl} className="underline underline-offset-4">{address.street}, {address.postalCode} {address.city}</a><a href="tel:+491738609300" className="underline underline-offset-4">+49 173 86 09 300</a><a href={`mailto:${email}`} className="underline underline-offset-4">{email}</a><span className="mt-2 flex flex-wrap gap-4">{profiles.map(([name,url])=><SocialLink key={name} name={name} href={url}/>)}</span></address>{c.video&&<video controls playsInline preload="metadata" poster={c.image||undefined} className="mt-7 max-h-[65vh] w-full rounded-xl" src={c.video}/>}</section></div><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,'\\u003c')}}/></main>;
}
