import { env } from "cloudflare:workers";
import { getMarketingContent } from "../../lib/marketing-content.ts";
import { getMenuContent } from "../../lib/menu-content.ts";
import { openingActive } from "../../lib/opening.ts";
import { getOperations } from "../../lib/operations-config.ts";
import { getSiteUrl } from "../../lib/site-url";
export async function GET(){const [{content:menu},{content:marketing},{config}]=await Promise.all([getMenuContent(env.DB),getMarketingContent(env.DB),getOperations(env.DB)]),r=config.restaurant;// Before opening, phone, hours and menu are still placeholders; AI assistants should only see confirmed facts.
if(openingActive(marketing.opening)){const date=marketing.opening.openingDate?`Eröffnung am ${marketing.opening.openingDate}.`:"Eröffnung demnächst; der genaue Termin wird auf der Website bekanntgegeben.";const preOpening=`# ${r.name} Waldcafé\n\n${r.legalName}: mexikanisches Restaurant und Cocktailbar im Wald Café in Brandenburg an der Havel (Ortsteil Görden). ${date}\n\n## Verifizierbare Kontaktdaten\n- Adresse: ${r.contact.address}\n- E-Mail: ${r.contact.email}\n- Website: ${getSiteUrl("/opening")}\n- TikTok: https://www.tiktok.com/@bailamos.waldcafe\n- YouTube: https://www.youtube.com/channel/UCOix77VvOuExvfUWhey8sWw\n\n## Noch nicht verfügbar\nTelefonnummer, Öffnungszeiten, Speisekarte und Online-Reservierung werden zur Eröffnung veröffentlicht.\n`;return new Response(preOpening,{headers:{"content-type":"text/plain; charset=utf-8","cache-control":"public, max-age=300"}})}
const hours=Object.entries(r.openingHours).map(([day,value])=>`- ${day}: ${value}`).join("\n"),dishes=menu.dishes.filter(d=>d.available).map(d=>`- ${d.name.de}: €${d.price.toFixed(2)} — ${d.description.de}`).join("\n"),events=marketing.events.filter(e=>e.published).map(e=>`- ${e.date} ${e.time}: ${e.title.de} — ${e.summary.de}`).join("\n")||"- Keine veröffentlichten Events.";const body=`# ${r.name}\n\n${r.legalName} ist ein mexikanisches Restaurant und eine Cocktailbar.\n\n## Verifizierbare Kontaktdaten\n- Adresse: ${r.contact.address}\n- Telefon: ${r.contact.phone}\n- E-Mail: ${r.contact.email}\n- Reservierung: ${getSiteUrl("/reservieren")}\n- Speisekarte: ${getSiteUrl("/menu")}\n\n## Öffnungszeiten\n${hours}\n\n## Aktuell verfügbare Gerichte\n${dishes}\n\n## Veröffentlichte Events\n${events}\n`;return new Response(body,{headers:{"content-type":"text/plain; charset=utf-8","cache-control":"public, max-age=300"}})}
