import assert from 'node:assert/strict';
import {defaultOpening,openingActive,revealDate,validateOpening} from '../lib/opening.ts';
import {validateMarketingContent} from '../lib/marketing-content.ts';
import defaults from '../data/marketing.json' with {type:'json'};
const config={...defaultOpening,autoReveal:true,openingDate:'2026-11-15'};
assert.equal(revealDate(config.openingDate),'2026-11-13');
assert.equal(openingActive(config,new Date('2026-11-12T22:59:59Z')),true);
assert.equal(openingActive(config,new Date('2026-11-12T23:00:00Z')),false);
assert.equal(openingActive({...config,enabled:false}),false);
assert.equal(openingActive({...defaultOpening,openingDate:''}),true);
assert.equal(revealDate('2026-03-01'),'2026-02-27');
assert.equal(openingActive({...config,openingDate:'2026-07-15'},new Date('2026-07-12T22:00:00Z')),false);
assert.throws(()=>validateOpening({...config,openingDate:''}));
assert.throws(()=>validateOpening({...config,openingDate:'2026-02-30'}));
assert.throws(()=>validateOpening({...config,image:'//example.org/a.jpg'}));
const migrated=validateMarketingContent(defaults);
assert.equal(migrated.opening.enabled,true);
assert.equal(migrated.events.filter(e=>e.id==='bailamos-opening').length,1);
assert.equal(migrated.events.find(e=>e.id==='bailamos-opening').published,false);
assert.equal(validateMarketingContent(migrated).events.filter(e=>e.id==='bailamos-opening').length,1);
assert.throws(()=>validateMarketingContent({...migrated,events:[{...migrated.events.find(e=>e.id==='bailamos-opening'),published:true}]}));
assert.equal(validateMarketingContent({...migrated,opening:{...migrated.opening,enabled:false}}).opening.enabled,false);
console.log('PASS: manual release, Berlin summer/winter midnight, two-calendar-day reveal, invalid dates/media, backward compatibility, opening draft and publication validation');
